image: atlassian/default-image:4

pipelines:
  branches:
    main:
      - step:
          name: Build and Deploy
          caches:
            - node
          script:
            - curl -L https://github.com/kristoff-it/zine/releases/download/v0.11.3/zine-linux-x86_64.tar.gz -o zine.tar.gz
            - tar -xzf zine.tar.gz
            - chmod +x zine
            - ./zine release
            - npm install -g wrangler
            - wrangler pages deploy public --project-name pratyay --branch n