image: atlassian/default-image:4

pipelines:
  branches:
    main:
      - step:
          name: Build and Deploy
          caches:
            - node
          script:
            - curl -fsSL https://github.com/kristoff-it/zine/releases/download/v0.11.3/x86_64-linux-musl.tar.xz -o zine.tar.gz
            - tar -xvf zine.tar.gz
            - chmod +x zine
            - ./zine release
            - npm install wrangler
            - npx wrangler pages deploy public --project-name pratyay --branch main
