[tools]
fd = "latest"
"github:kristoff-it/ziggy" = "latest"
"github:kristoff-it/zine" = "latest"
"github:neurocyte/flow" = "latest"
"github:pratyay360/md2smd" = "main"
node = "latest"
superhtml = "latest"
wrangler = { version = "latest", allow_builds = ["esbuild", "sharp", "workerd"] }

[settings]
experimental = true

[tasks]
fetch = "mise deps && node scripts/fetch.js"
build = { run = ["mise run fetch", "zine release -f", "npx -y pagefind --site public"] }
dev = "zine"
deploy = "wrangler pages deploy public/ --project-name pratyay"
