name: cloudflare pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup Zine
        uses: kristoff-it/setup-zine@main
        with:
          version: v0.12.0

      - name: Build
        run: zine release

      - name: Deploy
        uses: cloudflare/wrangler-action@main
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public/ --project-name pratyay
          githubToken: ${{ github.token }}


      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@main
      #   with:
      #     github_token: ${{ github.token }}
      #     publish_dir: ./public
