name: cloudflare pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [content_update, blog_update]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/jdx/mise:latest
    steps:
      - name: checkout code
        uses: actions/checkout@main

      - name: Install dependencies & deploy
        run: |
            mise deps
            mise run fetch
            mise run build
            mise run deploy
        env:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
